"use client";

import Link from "next/link";
import { useState } from "react";
import { LEGAL_UPDATED_AT, SUPPORT_EMAIL } from "@/lib/legal/release";

type Lang = "ja" | "en";
const UPDATED_AT = LEGAL_UPDATED_AT;
type Section = { title: string; body: string[] };

const ja: Section[] = [
  { title: "1. 本規約について", body: ["本規約は、Trendre（以下「本サービス」）およびTrendre Linkの利用条件を定めるものです。利用者は、本規約およびプライバシーポリシーを確認のうえ利用します。"] },
  { title: "2. 現在提供するサービス", body: ["Trendre Linkは、Creatorがプロフィール、SNSリンク、ポートフォリオ、Link item、公開メニュー・価格などを公開し、閲覧者から仕事相談を受け取るための機能です。", "仕事相談の送信は、契約、正式発注、報酬の支払いその他の取引成立を意味しません。また、当社は仕事の獲得、返信、案件成立を保証しません。Marketplaceに関する取引条件は、正式公開時に別途定めます。"] },
  { title: "3. Creator登録とアカウント", body: ["Creator登録は18歳以上の方に限ります。登録情報は真実かつ最新の内容を入力し、アカウントおよびログイン情報を適切に管理してください。", "当社は、虚偽登録、なりすまし、規約違反、不正利用その他運営上不適切と判断した場合、登録拒否、機能制限、利用停止またはアカウント削除を行うことがあります。"] },
  { title: "4. 公開情報とCreatorの責任", body: ["Creatorが公開設定した表示名、avatar、cover、bio、SNSリンク、ポートフォリオ、Link item、メニュー・価格等はインターネット上で閲覧できる状態になります。", "Creatorは、公開・投稿する情報や素材について必要な権利を有し、著作権、肖像権、商標権、プライバシーその他の第三者の権利を侵害しないことを保証します。"] },
  { title: "5. 仕事相談", body: ["仕事相談フォームから受け取る氏名、メールアドレス、相談内容等は、相談への回答・連絡の目的で相談先Creatorへ共有されます。Creatorはこれらの情報を無関係な営業、spamその他不適切な目的に利用してはなりません。", "閲覧者は、虚偽情報の送信、spam、不正アクセス、サービス運営の妨害その他当社または第三者に損害を与える行為をしてはなりません。"] },
  { title: "6. 禁止事項", body: ["利用者は、法令・公序良俗・各SNS等の規約に反する行為、他者への嫌がらせや差別的言動、虚偽・なりすまし、権利侵害、スクレイピング、リバースエンジニアリング、不正アクセス、または当社が不適切と判断する行為をしてはなりません。"] },
  { title: "7. 退会・サービス変更・免責", body: ["利用者は当社所定の方法で退会を申し出ることができます。当社は必要に応じて本サービスを変更、追加、停止または終了できます。", "当社は、本サービスの完全性、継続性、特定目的への適合性、利用結果を保証しません。法令で認められる範囲で、当社は利用者間の連絡・相談・公開内容等から生じる損害について責任を負いません。ただし当社の故意または重過失による場合を除きます。"] },
  { title: "8. 規約変更・準拠法・管轄", body: ["当社は必要に応じて本規約を変更し、重要な変更はサービス上その他適切な方法で周知します。本規約は日本法に準拠し、本サービスに関する紛争は当社所在地を管轄する裁判所を第一審の専属的合意管轄裁判所とします。"] },
];
const en: Section[] = [
  { title: "1. These Terms", body: ["These Terms govern Trendre (the “Service”) and Trendre Link. Users must review these Terms and the Privacy Policy before using the Service."] },
  { title: "2. Currently available service", body: ["Trendre Link lets creators publish profiles, social links, portfolios, Link items, and public menus or prices, and receive work inquiries from visitors.", "Sending an inquiry does not create a contract, formal order, payment obligation, or any other transaction. We do not guarantee work opportunities, replies, or an engagement. Marketplace transaction terms will be published separately when that service is launched."] },
  { title: "3. Creator registration and accounts", body: ["Creator registration is available only to people aged 18 or over. Registration information must be truthful and current, and users are responsible for their accounts and credentials.", "We may refuse registration, limit features, suspend use, or remove an account for false information, impersonation, violations, misuse, or other operationally inappropriate conduct."] },
  { title: "4. Public information and creator responsibility", body: ["A creator’s display name, avatar, cover, bio, social links, portfolio, Link items, and public menus or prices may be visible on the internet when the creator chooses to publish them.", "Creators represent that they have the rights needed for their public information and materials and that they do not infringe copyrights, portrait rights, trademarks, privacy, or other third-party rights."] },
  { title: "5. Work inquiries", body: ["A visitor’s name, email address, and inquiry content are shared with the relevant creator solely so the creator can respond or contact the visitor. Creators must not use that information for unrelated sales, spam, or any improper purpose.", "Visitors must not submit false information, spam, unauthorized access attempts, service interference, or conduct that harms us or others."] },
  { title: "6. Prohibited conduct", body: ["Users must not violate law, public order, or third-party platform rules; harass others; impersonate; infringe rights; scrape; reverse engineer; access without authorization; interfere with the Service; or engage in conduct we reasonably deem inappropriate."] },
  { title: "7. Withdrawal, changes, and disclaimer", body: ["Users may request withdrawal by our prescribed method. We may modify, add, suspend, or discontinue the Service when necessary.", "We do not guarantee completeness, continuity, fitness for a particular purpose, or outcomes. To the extent permitted by law, we are not responsible for loss arising from user communications, inquiries, or public content, except where caused by our intentional misconduct or gross negligence."] },
  { title: "8. Changes, governing law, and jurisdiction", body: ["We may revise these Terms and will announce material changes through the Service or another appropriate method. These Terms are governed by Japanese law, and disputes are subject to the exclusive jurisdiction of the court having jurisdiction over our principal office as the court of first instance."] },
];

export default function TermsPage() { const [lang, setLang] = useState<Lang>("ja"); const sections = lang === "ja" ? ja : en; return <main className="min-h-screen bg-white text-slate-900"><div className="mx-auto max-w-3xl px-6 py-12 md:px-8"><header className="mb-9 flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-medium text-slate-500">Trendre</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{lang === "ja" ? "利用規約" : "Terms of Service"}</h1><p className="mt-3 text-sm text-slate-500">{lang === "ja" ? `最終更新日：${UPDATED_AT}` : `Last updated: ${UPDATED_AT}`}</p></div><div className="inline-flex rounded-full border border-slate-200 p-1"><button type="button" onClick={() => setLang("ja")} className={`rounded-full px-3 py-1.5 text-sm ${lang === "ja" ? "bg-slate-900 text-white" : "text-slate-600"}`}>日本語</button><button type="button" onClick={() => setLang("en")} className={`rounded-full px-3 py-1.5 text-sm ${lang === "en" ? "bg-slate-900 text-white" : "text-slate-600"}`}>English</button></div></header><div className="space-y-7">{sections.map((section) => <section key={section.title} className="rounded-2xl border border-slate-200 p-5 md:p-6"><h2 className="text-lg font-semibold">{section.title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-slate-700">{section.body.map((line) => <p key={line}>{line}</p>)}</div></section>)}</div><nav className="mt-10 flex flex-wrap gap-4 text-sm"><Link href="/privacy" className="underline underline-offset-4">{lang === "ja" ? "プライバシーポリシー" : "Privacy Policy"}</Link><Link href="/legal" className="underline underline-offset-4">{lang === "ja" ? "事業者情報" : "Business information"}</Link></nav></div></main>; }
ja.push({ title: "お問い合わせ", body: [`利用規約に関するお問い合わせ、サービス利用者サポート、ならびに常時掲載していない事業者情報の開示請求は、${SUPPORT_EMAIL}で受け付けます。`] });
en.push({ title: "Contact", body: [`For support, questions about these Terms, and requests for statutory business information not continuously displayed, contact ${SUPPORT_EMAIL}.`] });
