import type { AppLocale } from "./types";

export const creatorMenuCommonDictionary = {
  ja: { setup: "メニュー設定", preview: "プレビュー", displayPrice: "表示価格", assetUse: "素材利用あり", noReuse: "二次利用不可", reuseOk: "二次利用可", notSet: "未設定", errorTitle: "エラー", manage: "管理", live: "公開中", private: "非公開", genericMenu: "メニュー" },
  en: { setup: "Menu setup", preview: "Preview", displayPrice: "Display price", assetUse: "Asset use", noReuse: "No reuse", reuseOk: "Reuse OK", notSet: "Not set", errorTitle: "Error", manage: "Manage", live: "Live", private: "Private", genericMenu: "Menu" },
  ko: { setup: "PR 메뉴 설정", preview: "미리보기", displayPrice: "표시 가격", assetUse: "소재 사용 가능", noReuse: "2차 활용 불가", reuseOk: "2차 활용 가능", notSet: "미설정", errorTitle: "오류", manage: "관리", live: "공개 중", private: "비공개", genericMenu: "PR 메뉴" },
  "zh-TW": { setup: "PR 方案設定", preview: "預覽", displayPrice: "顯示價格", assetUse: "可使用素材", noReuse: "不可二次使用", reuseOk: "可二次使用", notSet: "尚未設定", errorTitle: "錯誤", manage: "管理", live: "公開中", private: "不公開", genericMenu: "PR 方案" },
} satisfies Record<AppLocale, Record<string, string>>;

export const creatorMenuEditorDictionary = {
  ja: { createTitle:"メニュー作成", editTitle:"メニュー編集", createSubtitle:"企業が注文しやすい形で、販売メニューを作成します。", editSubtitle:"企業に表示される内容を、わかりやすく整えます。", back:"戻る", create:"作成する", creating:"作成中...", update:"更新する", updating:"更新中...", loading:"読み込み中...", loginRequired:"ログインしてください", creatorNotFound:"クリエイター情報が見つかりません", notFound:"メニューが見つかりませんでした", saveFailed:"メニューの保存に失敗しました", updateFailed:"メニューの更新に失敗しました", menu:"SNS種別", menuHelp:"販売するSNS種別・納品内容を1つ選択します。", price:"価格", createPriceHelp:"企業が注文する際の基本価格です。", editPriceHelp:"企業が注文する際の基本価格です。あとからいつでも変更できます。", yenOnly:"JPY / 日本円", pricePlaceholder:"例）11,000", secondaryUseTitle:"二次利用", secondaryUseBody:"納品物は広告ブランドのSNSによって二次利用・引用されることがあります。", materialUseNote:"素材はブランドのSNSやHPにて使用されることがあります。", denySecondaryUse:"二次利用を認めない", menuRequired:"SNS種別を選択してください", priceRequired:"価格を入力してください", priceInvalid:"3,000円以上で入力してください", previewBody:"メニューを選択してください", public:"公開中", private:"非公開" },
  en: { createTitle:"Create menu", editTitle:"Edit menu", createSubtitle:"Create a clean, orderable menu for brands.", editSubtitle:"Polish the content shown to brands.", back:"Back", create:"Create", creating:"Creating...", update:"Update", updating:"Updating...", loading:"Loading...", loginRequired:"Please log in", creatorNotFound:"Creator information was not found", notFound:"Menu was not found", saveFailed:"Failed to save the menu", updateFailed:"Failed to update the menu", menu:"SNS type", menuHelp:"Choose one SNS type or deliverable you can offer.", price:"Price", createPriceHelp:"Base price brands will pay when ordering.", editPriceHelp:"Base price brands will pay when ordering.", yenOnly:"JPY / Japanese yen", pricePlaceholder:"Example: 11,000", secondaryUseTitle:"Secondary use", secondaryUseBody:"Deliverables may be reused or quoted by the brand on its social accounts.", materialUseNote:"Assets may be used on the brand's social accounts or website.", denySecondaryUse:"Do not allow secondary use", menuRequired:"Please select a menu", priceRequired:"Please enter a price", priceInvalid:"Please enter JPY 3,000 or more", previewBody:"Select a menu", public:"Public", private:"Private" },
  ko: { createTitle:"PR 메뉴 만들기", editTitle:"PR 메뉴 수정", createSubtitle:"브랜드가 바로 주문할 수 있도록 제공 내용을 등록하세요.", editSubtitle:"브랜드에 표시될 내용을 알기 쉽게 정리하세요.", back:"뒤로", create:"만들기", creating:"만드는 중...", update:"저장", updating:"저장 중...", loading:"불러오는 중...", loginRequired:"로그인해 주세요", creatorNotFound:"크리에이터 정보를 찾을 수 없습니다", notFound:"PR 메뉴를 찾을 수 없습니다", saveFailed:"PR 메뉴를 저장하지 못했습니다", updateFailed:"PR 메뉴를 수정하지 못했습니다", menu:"제공 유형", menuHelp:"제공할 SNS 콘텐츠나 납품 유형을 하나 선택하세요.", price:"가격", createPriceHelp:"브랜드가 주문할 때 적용되는 기본 가격입니다.", editPriceHelp:"브랜드가 주문할 때 적용되는 기본 가격이며 언제든 변경할 수 있습니다.", yenOnly:"JPY / 일본 엔", pricePlaceholder:"예: 11,000", secondaryUseTitle:"2차 활용", secondaryUseBody:"납품물은 브랜드의 SNS에서 재사용되거나 인용될 수 있습니다.", materialUseNote:"소재는 브랜드의 SNS 또는 웹사이트에 사용될 수 있습니다.", denySecondaryUse:"2차 활용 허용 안 함", menuRequired:"제공 유형을 선택해 주세요", priceRequired:"가격을 입력해 주세요", priceInvalid:"3,000엔 이상 입력해 주세요", previewBody:"PR 메뉴를 선택해 주세요", public:"공개 중", private:"비공개" },
  "zh-TW": { createTitle:"新增 PR 方案", editTitle:"編輯 PR 方案", createSubtitle:"設定清楚的合作內容，讓品牌能直接下單。", editSubtitle:"整理品牌會看到的方案內容。", back:"返回", create:"新增", creating:"新增中...", update:"儲存", updating:"儲存中...", loading:"載入中...", loginRequired:"請先登入", creatorNotFound:"找不到創作者資料", notFound:"找不到這個 PR 方案", saveFailed:"無法儲存 PR 方案", updateFailed:"無法更新 PR 方案", menu:"提供項目", menuHelp:"選擇一項可提供的社群內容或交付項目。", price:"價格", createPriceHelp:"品牌下單時支付的基本價格。", editPriceHelp:"品牌下單時支付的基本價格，之後可隨時調整。", yenOnly:"JPY / 日圓", pricePlaceholder:"例如：11,000", secondaryUseTitle:"二次使用", secondaryUseBody:"交付內容可能會由品牌在社群帳號中再次使用或引用。", materialUseNote:"素材可能會使用於品牌的社群帳號或網站。", denySecondaryUse:"不允許二次使用", menuRequired:"請選擇提供項目", priceRequired:"請輸入價格", priceInvalid:"請輸入 3,000 日圓以上的金額", previewBody:"請選擇 PR 方案", public:"公開中", private:"不公開" },
} satisfies Record<AppLocale, Record<string, string>>;

export const creatorMenuListDictionary = {
  ja:{title:"メニュー管理",subtitle:"メニューの公開状態と価格を管理できます。",loginRequired:"ログインしてください",creatorNotFound:"クリエイター情報が見つかりません",toggleFailed:"公開状態の切り替えに失敗しました",confirmDelete:"このメニューを削除しますか？企業側からも表示されなくなります。",deleteFailed:"削除に失敗しました",loadFailed:"メニューの取得に失敗しました",createNew:"作成",emptyTitle:"まだメニューがありません",emptyCreatorOnly:"Instagram投稿、TikTok動画、UGC制作など、提供したい内容と参考価格を登録しましょう。",emptyMarketplace:"Instagram投稿、TikTok動画、UGC制作など、企業が注文できるメニューを作成しましょう。",price:"価格",secondaryUseDenied:"二次利用不可",makePrivate:"非公開にする",makePublic:"公開する",edit:"編集",delete:"削除",deleting:"削除中",updating:"更新中",legacyCreatorOnly:"旧形式の参考価格です。編集画面で内容と価格を確認できます。",legacyMarketplace:"旧形式の参考価格です。編集画面で固定価格にすると注文されやすくなります。",viewAccount:"SNSを開く",serviceCount:(all:number,live:number)=>`${all}件のサービス · ${live}件を公開中`},
  en:{title:"Menu management",subtitle:"Manage menu pricing and visibility.",loginRequired:"Please log in",creatorNotFound:"Creator information was not found",toggleFailed:"Failed to change visibility",confirmDelete:"Delete this menu? It will no longer be visible to companies.",deleteFailed:"Failed to delete the menu",loadFailed:"Failed to load menus",createNew:"Create",emptyTitle:"No menus yet",emptyCreatorOnly:"Register the services you offer and their reference rates, such as Instagram posts, TikTok videos, or UGC creation.",emptyMarketplace:"Create menus companies can order, such as Instagram posts, TikTok videos, or UGC creation.",price:"Price",secondaryUseDenied:"No reuse",makePrivate:"Make private",makePublic:"Make public",edit:"Edit",delete:"Delete",deleting:"Deleting",updating:"Updating",legacyCreatorOnly:"This menu uses a legacy reference price. Review its details and price from the edit page.",legacyMarketplace:"This menu uses a legacy reference price. Set a fixed price from the edit page.",viewAccount:"Open SNS",serviceCount:(all:number,live:number)=>`${all} offerings · ${live} live`},
  ko:{title:"PR 메뉴 관리",subtitle:"PR 메뉴의 가격과 공개 상태를 관리하세요.",loginRequired:"로그인해 주세요",creatorNotFound:"크리에이터 정보를 찾을 수 없습니다",toggleFailed:"공개 상태를 변경하지 못했습니다",confirmDelete:"이 PR 메뉴를 삭제할까요? 브랜드에도 더 이상 표시되지 않습니다.",deleteFailed:"PR 메뉴를 삭제하지 못했습니다",loadFailed:"PR 메뉴를 불러오지 못했습니다",createNew:"만들기",emptyTitle:"아직 PR 메뉴가 없습니다",emptyCreatorOnly:"Instagram 게시물, TikTok 영상, UGC 제작 등 제공할 내용과 참고 가격을 등록해 보세요.",emptyMarketplace:"브랜드가 주문할 수 있도록 Instagram 게시물, TikTok 영상, UGC 제작 등의 PR 메뉴를 만들어 보세요.",price:"가격",secondaryUseDenied:"2차 활용 불가",makePrivate:"비공개로 전환",makePublic:"공개로 전환",edit:"수정",delete:"삭제",deleting:"삭제 중",updating:"변경 중",legacyCreatorOnly:"이전 형식의 참고 가격입니다. 수정 화면에서 내용과 가격을 확인하세요.",legacyMarketplace:"이전 형식의 참고 가격입니다. 수정 화면에서 고정 가격을 설정하세요.",viewAccount:"SNS 열기",serviceCount:(all:number,live:number)=>`서비스 ${all}개 · ${live}개 공개 중`},
  "zh-TW":{title:"PR 方案管理",subtitle:"管理 PR 方案的價格與公開狀態。",loginRequired:"請先登入",creatorNotFound:"找不到創作者資料",toggleFailed:"無法切換公開狀態",confirmDelete:"要刪除這個 PR 方案嗎？刪除後品牌將無法查看。",deleteFailed:"無法刪除 PR 方案",loadFailed:"無法載入 PR 方案",createNew:"新增",emptyTitle:"目前還沒有 PR 方案",emptyCreatorOnly:"新增 Instagram 貼文、TikTok 影片或 UGC 製作等服務內容與參考價格。",emptyMarketplace:"建立 Instagram 貼文、TikTok 影片或 UGC 製作等品牌可直接下單的 PR 方案。",price:"價格",secondaryUseDenied:"不可二次使用",makePrivate:"設為不公開",makePublic:"設為公開",edit:"編輯",delete:"刪除",deleting:"刪除中",updating:"更新中",legacyCreatorOnly:"這是舊格式的參考價格，請前往編輯頁面確認內容與價格。",legacyMarketplace:"這是舊格式的參考價格，請前往編輯頁面設定固定價格。",viewAccount:"開啟社群帳號",serviceCount:(all:number,live:number)=>`${all} 項服務 · ${live} 項公開中`},
} satisfies Record<AppLocale, Record<string, string | ((all: number, live: number) => string)>>;

type MenuOptionCopy = { label: string; help: string };
export const creatorMenuOptionDictionary: Record<AppLocale, Record<string, MenuOptionCopy>> = {
  ja:{"Instagram投稿":{label:"Instagram投稿",help:"Instagramのフィード投稿として紹介します。"},"Instagramリール":{label:"Instagramリール",help:"Instagramリール動画として投稿します。"},"Instagramストーリーズ":{label:"Instagramストーリーズ",help:"Instagramストーリーズで紹介します。"},"TikTok投稿":{label:"TikTok投稿",help:"TikTok動画として投稿します。"},"YouTubeショート":{label:"YouTubeショート",help:"YouTube Shortsとして投稿します。"},"YouTube動画":{label:"YouTube動画",help:"YouTube動画として投稿します。"},"投稿なし・動画素材のみ納品":{label:"動画素材のみ納品",help:"広告やSNSで使える動画素材だけを納品します。自分のアカウントには投稿しません。"},"投稿なし・写真素材のみ納品":{label:"写真素材のみ納品",help:"広告やSNSで使える写真素材だけを納品します。自分のアカウントには投稿しません。"},"イベント訪問":{label:"イベント訪問",help:"店舗・イベント・展示会などに訪問して投稿または素材制作を行います。"},"その他":{label:"その他",help:"上記以外のメニューです。"}},
  en:{"Instagram投稿":{label:"Instagram Feed Post",help:"A feed post published on Instagram."},"Instagramリール":{label:"Instagram Reel",help:"A short-form video published as an Instagram Reel."},"Instagramストーリーズ":{label:"Instagram Stories",help:"A story placement published on Instagram."},"TikTok投稿":{label:"TikTok Video",help:"A video published on TikTok."},"YouTubeショート":{label:"YouTube Short",help:"A short-form video published on YouTube Shorts."},"YouTube動画":{label:"YouTube Video",help:"A video published on YouTube."},"投稿なし・動画素材のみ納品":{label:"Video asset only",help:"Deliver video assets only. You do not post on your own account."},"投稿なし・写真素材のみ納品":{label:"Photo asset only",help:"Deliver photo assets only. You do not post on your own account."},"イベント訪問":{label:"Event visit",help:"Visit an event, store, or location for content creation."},"その他":{label:"Other",help:"Use this for custom services."}},
  ko:{"Instagram投稿":{label:"Instagram 피드 게시물",help:"Instagram 피드 게시물로 브랜드를 소개합니다."},"Instagramリール":{label:"Instagram 릴스",help:"Instagram 릴스 영상을 제작해 게시합니다."},"Instagramストーリーズ":{label:"Instagram 스토리",help:"Instagram 스토리로 브랜드를 소개합니다."},"TikTok投稿":{label:"TikTok 영상",help:"TikTok 영상을 제작해 게시합니다."},"YouTubeショート":{label:"YouTube Shorts",help:"YouTube Shorts 영상을 제작해 게시합니다."},"YouTube動画":{label:"YouTube 영상",help:"YouTube 영상을 제작해 게시합니다."},"投稿なし・動画素材のみ納品":{label:"영상 소재만 납품",help:"광고와 SNS에 사용할 영상 소재만 납품하며 내 계정에는 게시하지 않습니다."},"投稿なし・写真素材のみ納品":{label:"사진 소재만 납품",help:"광고와 SNS에 사용할 사진 소재만 납품하며 내 계정에는 게시하지 않습니다."},"イベント訪問":{label:"이벤트 방문",help:"매장, 이벤트 또는 전시회에 방문해 콘텐츠를 제작합니다."},"その他":{label:"기타",help:"목록에 없는 맞춤 서비스를 등록합니다."}},
  "zh-TW":{"Instagram投稿":{label:"Instagram 貼文",help:"以 Instagram 動態貼文介紹品牌。"},"Instagramリール":{label:"Instagram Reels",help:"製作並發布 Instagram Reels 短影音。"},"Instagramストーリーズ":{label:"Instagram 限時動態",help:"透過 Instagram 限時動態介紹品牌。"},"TikTok投稿":{label:"TikTok 影片",help:"製作並發布 TikTok 影片。"},"YouTubeショート":{label:"YouTube Shorts",help:"製作並發布 YouTube Shorts 短影音。"},"YouTube動画":{label:"YouTube 影片",help:"製作並發布 YouTube 影片。"},"投稿なし・動画素材のみ納品":{label:"僅交付影片素材",help:"僅交付可用於廣告或社群平台的影片素材，不會發布在自己的帳號。"},"投稿なし・写真素材のみ納品":{label:"僅交付照片素材",help:"僅交付可用於廣告或社群平台的照片素材，不會發布在自己的帳號。"},"イベント訪問":{label:"活動到訪",help:"前往店家、活動或展覽現場製作內容。"},"その他":{label:"其他",help:"新增上述項目以外的客製服務。"}},
};

export function localizeCreatorMenuRecord(
  locale: AppLocale,
  title: string,
  description: string | null,
): { title: string; description: string | null } {
  const entries = Object.entries(creatorMenuOptionDictionary.ja);
  const titleCanonical = entries.find(([value, copy]) => value === title || copy.label === title)?.[0]
    ?? Object.entries(creatorMenuOptionDictionary.en).find(([, copy]) => copy.label === title)?.[0];
  const descriptionCanonical = description
    ? entries.find(([, copy]) => copy.help === description)?.[0]
      ?? Object.entries(creatorMenuOptionDictionary.en).find(([, copy]) => copy.help === description)?.[0]
    : undefined;
  return {
    title: titleCanonical ? creatorMenuOptionDictionary[locale][titleCanonical].label : title,
    description: descriptionCanonical
      ? creatorMenuOptionDictionary[locale][descriptionCanonical].help
      : description,
  };
}

export const creatorMenuFormatDictionary: Record<AppLocale, Record<string, string>> = {
  ja:{post:"投稿",reel:"リール",stories:"ストーリーズ",video:"動画",short:"ショート",videoAsset:"動画素材",photoAsset:"写真素材",visit:"訪問",short_video:"ショート動画",story:"ストーリー",ugc:"UGC制作",ugc_video:"動画素材",ugc_photo:"写真素材",event_visit:"訪問",package:"セット",other:"その他"},
  en:{post:"Post",reel:"Reel",stories:"Stories",video:"Video",short:"Short",videoAsset:"Video asset",photoAsset:"Photo asset",visit:"Visit",short_video:"Short video",story:"Story",ugc:"UGC",ugc_video:"Video asset",ugc_photo:"Photo asset",event_visit:"Visit",package:"Package",other:"Other"},
  ko:{post:"게시물",reel:"릴스",stories:"스토리",video:"영상",short:"Shorts",videoAsset:"영상 소재",photoAsset:"사진 소재",visit:"방문",short_video:"숏폼 영상",story:"스토리",ugc:"UGC 제작",ugc_video:"영상 소재",ugc_photo:"사진 소재",event_visit:"방문",package:"패키지",other:"기타"},
  "zh-TW":{post:"貼文",reel:"Reels",stories:"限時動態",video:"影片",short:"Shorts",videoAsset:"影片素材",photoAsset:"照片素材",visit:"到訪",short_video:"短影音",story:"限時動態",ugc:"UGC 製作",ugc_video:"影片素材",ugc_photo:"照片素材",event_visit:"到訪",package:"組合方案",other:"其他"},
};
