import type { AppLocale } from "./types";

export type CreatorJobsCopy = {
  title:string;jobs:string;messages:string;emptyJobs:string;emptyJobsBody:string;emptyMessages:string;emptyMessagesBody:string;noMessage:string;loadError:string;retry:string;yesterday:string;daysAgo:(days:number)=>string;untitled:string;
  actions: Record<string,{title:string;body:string}>;
};

export const creatorJobsDictionary = {
  ja:{title:"仕事",jobs:"進行中",messages:"メッセージ",emptyJobs:"進行中の仕事はありません",emptyJobsBody:"成立した依頼は、ここで準備から納品まで進めます。",emptyMessages:"メッセージはありません",emptyMessagesBody:"案件のやりとりが始まると、ここに表示されます。",noMessage:"まだメッセージはありません",loadError:"仕事を読み込めませんでした。",retry:"再読み込み",yesterday:"昨日",daysAgo:(days:number)=>`${days}日前`,untitled:"案件",actions:{revision:{title:"修正内容を確認してください",body:"内容を確認して再提出へ進みます"},review:{title:"依頼元の確認待ち",body:"納品内容を確認してもらっています"},address:{title:"配送先を入力してください",body:"商品の発送に必要な情報を登録します"},shipment:{title:"商品の到着を待っています",body:"届いたら受取確認へ進みます"},schedule:{title:"日程を調整してください",body:"候補日を確認して日程を決めます"},materials:{title:"素材を確認してください",body:"受け取った素材を確認して作業を始めます"},next:{title:"次の作業を確認してください",body:"案件を開くと、今必要な作業を確認できます"}}},
  en:{title:"Jobs",jobs:"Active",messages:"Messages",emptyJobs:"No active jobs",emptyJobsBody:"Accepted work will appear here from preparation through delivery.",emptyMessages:"No messages",emptyMessagesBody:"Job conversations will appear here.",noMessage:"No messages yet",loadError:"Could not load jobs.",retry:"Reload",yesterday:"Yesterday",daysAgo:(days:number)=>`${days}d ago`,untitled:"Job",actions:{revision:{title:"Review requested changes",body:"Review the details and submit again"},review:{title:"Waiting for review",body:"The delivery is being reviewed"},address:{title:"Add a shipping address",body:"Add the details needed for shipping"},shipment:{title:"Waiting for the product",body:"Confirm when the product arrives"},schedule:{title:"Schedule the visit",body:"Review dates and confirm the schedule"},materials:{title:"Review the materials",body:"Review the supplied materials and start"},next:{title:"Check your next step",body:"Open the job to see what to do next"}}},
  ko:{title:"협업",jobs:"진행 중",messages:"메시지",emptyJobs:"진행 중인 협업이 없습니다",emptyJobsBody:"수락한 의뢰는 준비부터 납품까지 이곳에서 진행할 수 있어요.",emptyMessages:"메시지가 없습니다",emptyMessagesBody:"협업 대화가 시작되면 이곳에 표시됩니다.",noMessage:"아직 메시지가 없습니다",loadError:"협업을 불러오지 못했습니다.",retry:"다시 불러오기",yesterday:"어제",daysAgo:(days:number)=>`${days}일 전`,untitled:"협업",actions:{revision:{title:"수정 요청을 확인해 주세요",body:"요청 내용을 확인하고 다시 제출하세요"},review:{title:"브랜드 확인 대기 중",body:"브랜드가 제출한 내용을 확인하고 있어요"},address:{title:"배송지를 입력해 주세요",body:"상품 배송에 필요한 정보를 등록하세요"},shipment:{title:"상품 배송을 기다리고 있어요",body:"상품이 도착하면 수령을 확인해 주세요"},schedule:{title:"방문 일정을 조율해 주세요",body:"후보 날짜를 확인하고 일정을 정하세요"},materials:{title:"제공된 소재를 확인해 주세요",body:"소재를 확인한 후 작업을 시작하세요"},next:{title:"다음 할 일을 확인해 주세요",body:"협업을 열어 지금 필요한 작업을 확인하세요"}}},
  "zh-TW":{title:"合作",jobs:"進行中",messages:"訊息",emptyJobs:"目前沒有進行中的合作",emptyJobsBody:"接受邀約後，可在這裡完成準備、製作與交付。",emptyMessages:"目前沒有訊息",emptyMessagesBody:"合作對話開始後會顯示在這裡。",noMessage:"目前還沒有訊息",loadError:"無法載入合作內容。",retry:"重新載入",yesterday:"昨天",daysAgo:(days:number)=>`${days} 天前`,untitled:"合作案件",actions:{revision:{title:"請確認修改要求",body:"確認內容後重新提交"},review:{title:"等待品牌確認",body:"品牌正在確認提交內容"},address:{title:"請填寫收件地址",body:"登記商品寄送所需資訊"},shipment:{title:"等待商品送達",body:"收到商品後請確認收件"},schedule:{title:"請安排到訪日期",body:"確認可選日期並敲定行程"},materials:{title:"請確認提供的素材",body:"確認素材後即可開始製作"},next:{title:"查看下一步",body:"開啟合作案件，確認目前需要處理的事項"}}},
} satisfies Record<AppLocale, CreatorJobsCopy>;
