import type { AppLocale } from "./types";

export type CreatorRequestsCopy={title:string;subtitle:string;actionBubble:string;actionBody:string;noOrdersShort:string;fetchError:string;partialFetchError:string;authTimeout:string;unnamedProduct:string;orderDate:string;menu:string;payout:string;replyLimit:string;empty:string;emptyBody:string;profileCta:string;newMessage:string;checkDetail:string;errorTitle:string;noticeTitle:string;unreadLabel:string;unreadSuffix:string;notSet:string;expired:string;replyBy:(date:string)=>string};
export const creatorRequestsDictionary={
 ja:{title:"注文",subtitle:"受ける前の注文を確認できます。",actionBubble:"注文を確認しましょう",actionBody:"内容・報酬・実施条件を確認して、受けるか判断できます。",noOrdersShort:"新しい注文が届くと、ここに表示されます。",fetchError:"注文の取得に失敗しました。",partialFetchError:"一部の情報を取得できませんでした。注文自体は表示できる範囲で表示しています。",authTimeout:"ログイン情報の取得に時間がかかっています。ページを再読み込みしてください。",unnamedProduct:"商品名未設定",orderDate:"注文日",menu:"メニュー",payout:"受取予定",replyLimit:"返答期限",empty:"届いている注文はありません",emptyBody:"新しい注文が届くとここに表示されます。",profileCta:"プロフィールを整える",newMessage:"新着メッセージ",checkDetail:"内容を確認してください",errorTitle:"エラー",noticeTitle:"一部読み込みに失敗しました",unreadLabel:"新着",unreadSuffix:"件",notSet:"未設定",expired:"返答期限切れ",replyBy:(date:string)=>`返答期限 ${date}`},
 en:{title:"Orders",subtitle:"Review orders before accepting.",actionBubble:"Review your order",actionBody:"Check the details, payout, and requirements before deciding.",noOrdersShort:"New orders will appear here.",fetchError:"Failed to load orders.",partialFetchError:"Some information could not be loaded. Showing available orders.",authTimeout:"Loading your login session is taking too long. Please reload the page.",unnamedProduct:"No product name",orderDate:"Order date",menu:"Menu",payout:"Expected",replyLimit:"Reply by",empty:"No incoming orders",emptyBody:"New orders will appear here.",profileCta:"Update profile",newMessage:"New message",checkDetail:"Check details",errorTitle:"Error",noticeTitle:"Partial loading issue",unreadLabel:"New",unreadSuffix:"",notSet:"Not set",expired:"Expired",replyBy:(date:string)=>`Reply by ${date}`},
 ko:{title:"주문",subtitle:"수락하기 전 주문 내용을 확인하세요.",actionBubble:"새 주문을 확인해 주세요",actionBody:"내용, 예상 수익, 진행 조건을 확인한 후 수락 여부를 결정하세요.",noOrdersShort:"새 주문이 도착하면 이곳에 표시됩니다.",fetchError:"주문을 불러오지 못했습니다.",partialFetchError:"일부 정보를 불러오지 못했습니다. 확인 가능한 주문만 표시합니다.",authTimeout:"로그인 정보를 불러오는 데 시간이 걸리고 있습니다. 페이지를 새로고침해 주세요.",unnamedProduct:"상품명 미정",orderDate:"주문일",menu:"PR 메뉴",payout:"예상 수익",replyLimit:"답변 기한",empty:"도착한 주문이 없습니다",emptyBody:"새 주문이 도착하면 이곳에 표시됩니다.",profileCta:"프로필 업데이트",newMessage:"새 메시지",checkDetail:"내용을 확인해 주세요",errorTitle:"오류",noticeTitle:"일부 항목을 불러오지 못했습니다",unreadLabel:"신규",unreadSuffix:"개",notSet:"미설정",expired:"답변 기한 만료",replyBy:(date:string)=>`답변 기한 ${date}`},
 "zh-TW":{title:"訂單",subtitle:"接受前請先確認訂單內容。",actionBubble:"請確認新訂單",actionBody:"確認合作內容、預計收益與執行條件後，再決定是否接受。",noOrdersShort:"收到新訂單後會顯示在這裡。",fetchError:"無法載入訂單。",partialFetchError:"部分資訊無法載入，目前僅顯示可取得的訂單內容。",authTimeout:"登入資訊載入時間較長，請重新整理頁面。",unnamedProduct:"商品名稱未設定",orderDate:"訂單日期",menu:"PR 方案",payout:"預計收益",replyLimit:"回覆期限",empty:"目前沒有收到訂單",emptyBody:"收到新訂單後會顯示在這裡。",profileCta:"完善個人檔案",newMessage:"新訊息",checkDetail:"請確認內容",errorTitle:"錯誤",noticeTitle:"部分內容載入失敗",unreadLabel:"新訊息",unreadSuffix:"則",notSet:"尚未設定",expired:"已超過回覆期限",replyBy:(date:string)=>`回覆期限 ${date}`},
} satisfies Record<AppLocale,CreatorRequestsCopy>;

export const creatorRequestDetailDictionary={
 ja:{loading:"読み込み中...",loadFailed:"取得に失敗しました",notFound:"依頼が見つかりません",loadError:"取得エラー",dataError:"データ取得エラー",title:"依頼詳細",backToList:"一覧へ戻る",productName:"商品名",productUrl:"URL",requestedPlatform:"希望媒体",requestedBudget:"希望価格",secondaryUse:"二次利用希望",deadline:"期限",memo:"メモ",status:"ステータス",unset:"未設定",empty:"未入力",none:"なし",yes:"あり",no:"なし",createdAt:"作成日",deliverSectionTitle:"投稿URL提出",deliverPlaceholder:"Instagram投稿URLなど",deliverSubmit:"提出する",deliveredUrlLabel:"提出済みURL",accept:"承認する",reject:"拒否する",acceptConfirm:"本当に承認しますか？",rejectConfirm:"本当に拒否しますか？",actionError:"エラーが発生しました",acceptedAlert:"承認しました。",rejectedAlert:"拒否しました",deliverRequired:"投稿URLを入力してください",deliverFailed:"納品に失敗しました",deliveredAlert:"納品しました",networkError:"通信エラー",budget:(value:number)=>`¥${value.toLocaleString("ja-JP")}`},
 en:{loading:"Loading...",loadFailed:"Failed to load request.",notFound:"Request not found.",loadError:"Failed to load data.",dataError:"Data load error.",title:"Request Details",backToList:"Back to List",productName:"Product Name",productUrl:"URL",requestedPlatform:"Requested Platform",requestedBudget:"Requested Budget",secondaryUse:"Secondary Use",deadline:"Deadline",memo:"Memo",status:"Status",unset:"Not set",empty:"Not entered",none:"None",yes:"Yes",no:"No",createdAt:"Created At",deliverSectionTitle:"Submit Post URL",deliverPlaceholder:"Instagram post URL, etc.",deliverSubmit:"Submit",deliveredUrlLabel:"Submitted URL",accept:"Approve",reject:"Reject",acceptConfirm:"Are you sure you want to approve this request?",rejectConfirm:"Are you sure you want to reject this request?",actionError:"Something went wrong.",acceptedAlert:"Approved.",rejectedAlert:"Rejected.",deliverRequired:"Please enter the post URL.",deliverFailed:"Failed to submit delivery.",deliveredAlert:"Submitted successfully.",networkError:"Network error.",budget:(value:number)=>`JPY ${value.toLocaleString("en-US")}`},
 ko:{loading:"불러오는 중...",loadFailed:"의뢰를 불러오지 못했습니다",notFound:"의뢰를 찾을 수 없습니다",loadError:"정보를 불러오지 못했습니다",dataError:"데이터를 불러오지 못했습니다",title:"의뢰 상세",backToList:"목록으로",productName:"상품명",productUrl:"URL",requestedPlatform:"요청 플랫폼",requestedBudget:"제안 금액",secondaryUse:"2차 활용 요청",deadline:"마감일",memo:"메모",status:"상태",unset:"미설정",empty:"입력 없음",none:"없음",yes:"있음",no:"없음",createdAt:"등록일",deliverSectionTitle:"게시물 URL 제출",deliverPlaceholder:"Instagram 게시물 URL 등",deliverSubmit:"제출",deliveredUrlLabel:"제출한 URL",accept:"수락",reject:"거절",acceptConfirm:"이 의뢰를 수락할까요?",rejectConfirm:"이 의뢰를 거절할까요?",actionError:"처리 중 오류가 발생했습니다",acceptedAlert:"의뢰를 수락했습니다.",rejectedAlert:"의뢰를 거절했습니다.",deliverRequired:"게시물 URL을 입력해 주세요",deliverFailed:"납품 내용을 제출하지 못했습니다",deliveredAlert:"납품 내용을 제출했습니다",networkError:"네트워크 오류",budget:(value:number)=>`¥${value.toLocaleString("ko-KR")}`},
 "zh-TW":{loading:"載入中...",loadFailed:"無法載入邀約",notFound:"找不到邀約",loadError:"無法載入內容",dataError:"資料載入錯誤",title:"邀約詳情",backToList:"返回列表",productName:"商品名稱",productUrl:"URL",requestedPlatform:"指定平台",requestedBudget:"預算",secondaryUse:"二次使用需求",deadline:"截止日期",memo:"備註",status:"狀態",unset:"尚未設定",empty:"未填寫",none:"無",yes:"有",no:"無",createdAt:"建立日期",deliverSectionTitle:"提交貼文 URL",deliverPlaceholder:"例如 Instagram 貼文 URL",deliverSubmit:"提交",deliveredUrlLabel:"已提交的 URL",accept:"接受",reject:"婉拒",acceptConfirm:"要接受這則合作邀約嗎？",rejectConfirm:"要婉拒這則合作邀約嗎？",actionError:"處理時發生錯誤",acceptedAlert:"已接受邀約。",rejectedAlert:"已婉拒邀約。",deliverRequired:"請輸入貼文 URL",deliverFailed:"無法提交交付內容",deliveredAlert:"已提交交付內容",networkError:"網路錯誤",budget:(value:number)=>`¥${value.toLocaleString("zh-TW")}`},
} satisfies Record<AppLocale,Record<string,string|((value:number)=>string)>>;
