import type { AppLocale } from "./types";

export type CreatorOrdersCopy = {
  title:string;all:string;orders:string;quotes:string;emptyTitle:string;emptyBody:string;loadError:string;retry:string;
  newLabel:string;workInquiry:string;order:string;quoteRequest:string;reviewInquiry:string;newInquiry:string;orderDetails:string;reviewAndRespond:string;reviewRequest:string;amountPending:string;budgetDiscuss:string;checkDeadline:string;deadlinePassed:string;withinHours:(hours:number)=>string;withinDays:(days:number)=>string;
};

const common = {
  ja:{all:"すべて",orders:"注文",emptyTitle:"新しい依頼はありません",loadError:"受注情報を読み込めませんでした。",retry:"再読み込み",newLabel:"新着",workInquiry:"仕事相談",order:"注文",quoteRequest:"見積もり依頼",reviewInquiry:"相談内容を確認",newInquiry:"新しい相談",orderDetails:"注文内容",reviewAndRespond:"内容を確認して回答してください",reviewRequest:"依頼内容を確認してください",amountPending:"金額未設定",budgetDiscuss:"予算は要相談",checkDeadline:"回答期限を確認",deadlinePassed:"回答期限を過ぎています",withinHours:(hours:number)=>`${hours}時間以内に回答`,withinDays:(days:number)=>`${days}日以内に回答`},
  en:{all:"All",orders:"Orders",emptyTitle:"Nothing needs your attention",loadError:"Could not load orders.",retry:"Reload",newLabel:"New",workInquiry:"Work inquiry",order:"Order",quoteRequest:"Quote request",reviewInquiry:"Review inquiry",newInquiry:"New inquiry",orderDetails:"Order details",reviewAndRespond:"Review and respond",reviewRequest:"Review the request",amountPending:"Amount pending",budgetDiscuss:"Budget to discuss",checkDeadline:"Check reply deadline",deadlinePassed:"Reply deadline passed",withinHours:(hours:number)=>`Reply within ${hours}h`,withinDays:(days:number)=>`Reply within ${days}d`},
  ko:{all:"전체",orders:"주문",emptyTitle:"확인할 새 의뢰가 없습니다",loadError:"의뢰 목록을 불러오지 못했습니다.",retry:"다시 불러오기",newLabel:"신규",workInquiry:"협업 문의",order:"주문",quoteRequest:"견적 요청",reviewInquiry:"문의 내용 확인",newInquiry:"새로운 문의",orderDetails:"주문 내용",reviewAndRespond:"내용을 확인하고 답변해 주세요",reviewRequest:"의뢰 내용을 확인해 주세요",amountPending:"금액 미정",budgetDiscuss:"예산 협의 필요",checkDeadline:"답변 기한 확인",deadlinePassed:"답변 기한이 지났습니다",withinHours:(hours:number)=>`${hours}시간 이내 답변`,withinDays:(days:number)=>`${days}일 이내 답변`},
  "zh-TW":{all:"全部",orders:"訂單",emptyTitle:"目前沒有新的合作邀約",loadError:"無法載入邀約內容。",retry:"重新載入",newLabel:"新邀約",workInquiry:"合作諮詢",order:"訂單",quoteRequest:"報價需求",reviewInquiry:"查看諮詢內容",newInquiry:"新的諮詢",orderDetails:"訂單內容",reviewAndRespond:"請確認內容並回覆",reviewRequest:"請確認邀約內容",amountPending:"金額未定",budgetDiscuss:"預算待討論",checkDeadline:"查看回覆期限",deadlinePassed:"已超過回覆期限",withinHours:(hours:number)=>`請在 ${hours} 小時內回覆`,withinDays:(days:number)=>`請在 ${days} 天內回覆`},
} as const;

export function getCreatorOrdersCopy(locale:AppLocale,creatorOnly:boolean):CreatorOrdersCopy {
  const base=common[locale];
  const variants={
    ja:{title:creatorOnly?"仕事相談":"受注",quotes:creatorOnly?"仕事相談":"見積もり依頼",emptyBody:creatorOnly?"新しい仕事相談が届くと、ここに表示されます。":"注文や見積もり依頼が届くと、ここに表示されます。"},
    en:{title:creatorOnly?"Work inquiries":"Orders",quotes:creatorOnly?"Work inquiries":"Quote requests",emptyBody:creatorOnly?"New work inquiries will appear here.":"New orders and quote requests will appear here."},
    ko:{title:creatorOnly?"협업 문의":"의뢰",quotes:creatorOnly?"협업 문의":"견적 요청",emptyBody:creatorOnly?"새로운 협업 문의가 도착하면 이곳에 표시됩니다.":"새 주문이나 견적 요청이 도착하면 이곳에 표시됩니다."},
    "zh-TW":{title:creatorOnly?"合作諮詢":"合作邀約",quotes:creatorOnly?"合作諮詢":"報價需求",emptyBody:creatorOnly?"收到新的合作諮詢後會顯示在這裡。":"收到新訂單或報價需求後會顯示在這裡。"},
  }[locale];
  return {...base,...variants};
}

export const creatorQuoteStatusDictionary:Record<AppLocale,Record<string,string>>={
  ja:{new:"見積もりを作成してください",creator_reviewing:"見積もりを作成中",quoted:"企業の回答を待っています",sent:"企業の回答を待っています",accepted:"企業が見積もりを承認しました",declined:"企業が見積もりを見送りました",expired:"見積もりの期限が切れました",cancelled:"見積もりは取り消されています",unknown:"依頼内容を確認してください"},
  en:{new:"Create a quote",creator_reviewing:"Quote in progress",quoted:"Waiting for the company",sent:"Waiting for the company",accepted:"Quote approved",declined:"Quote declined",expired:"Quote expired",cancelled:"Quote cancelled",unknown:"Review the request"},
  ko:{new:"견적을 작성해 주세요",creator_reviewing:"견적 작성 중",quoted:"브랜드 답변 대기 중",sent:"브랜드 답변 대기 중",accepted:"브랜드가 견적을 수락했습니다",declined:"브랜드가 견적을 보류했습니다",expired:"견적 유효 기간이 지났습니다",cancelled:"견적이 취소되었습니다",unknown:"의뢰 내용을 확인해 주세요"},
  "zh-TW":{new:"請建立報價",creator_reviewing:"正在建立報價",quoted:"等待品牌回覆",sent:"等待品牌回覆",accepted:"品牌已接受報價",declined:"品牌未接受報價",expired:"報價已過期",cancelled:"報價已取消",unknown:"請確認邀約內容"},
};

export const creatorOrderDetailTranslations: Partial<Record<AppLocale, Record<string, string>>> = {
  ko: {
    loading:"불러오는 중...",notFound:"주문을 찾을 수 없습니다.",back:"뒤로",titleFallback:"주문 상세",menuContentTitle:"PR 메뉴 정보",orderContent:"주문 내용",preparationTitle:"시작 전 준비 사항",preparationBeforeAcceptTitle:"수락 전 확인",preparationChatButton:"채팅으로 문의",preparationChatDisabled:"주문을 수락한 후 필요한 내용을 채팅으로 조율할 수 있습니다.",preparationReadyLabel:"준비 완료",preparationWaitingLabel:"확인 필요",
    materialsConfirmTitle:"소재와 게시 정보를 확인해 주세요",materialsConfirmBody:"제공된 소재, 게시 조건, PR 표기와 유의 사항을 확인한 후 문제가 없으면 확인을 완료해 주세요.",materialsConfirmButton:"소재와 게시 정보를 확인했습니다",materialsConfirmLoading:"변경 중...",materialsConfirmConfirm:"소재와 게시 정보를 모두 확인했나요? 확인 후 납품 단계로 진행할 수 있습니다.",materialsConfirmFailed:"소재 확인 상태를 변경하지 못했습니다. 잠시 후 다시 시도해 주세요.",materialsConfirmedTitle:"소재와 게시 정보 확인 완료",materialsConfirmedBody:"콘텐츠 제작과 납품을 진행할 수 있는 상태입니다.",
    shippingAddressTitle:"배송지 공유",shippingAddressBody:"상품을 받을 배송지를 입력해 주세요. 의뢰한 브랜드에 공유됩니다.",shippingRecipientName:"받는 분",shippingPostalCode:"우편번호",shippingPrefecture:"시/도",shippingCity:"시/군/구",shippingAddressLine1:"상세 주소",shippingAddressLine2:"건물명·호수",shippingPhoneNumber:"전화번호",shippingNotes:"배송 메모",postalLookupButton:"주소 검색",postalLookupLoading:"검색 중...",postalLookupInvalid:"우편번호 7자리를 입력해 주세요.",postalLookupFailed:"주소를 자동 입력하지 못했습니다. 직접 입력해 주세요.",postalLookupNotFound:"주소를 찾을 수 없습니다. 우편번호를 확인해 주세요.",postalLookupApplied:"주소를 입력했습니다. 나머지 상세 주소를 입력해 주세요.",postalLookupMultiple:"검색 결과가 여러 개입니다. 필요한 경우 아래에서 다른 주소를 선택해 주세요.",postalLookupCandidateLabel:"주소 후보",shippingShareAddress:"배송지 공유",shippingUpdateAddress:"배송지 변경",shippingSharingAddress:"공유 중...",shippingAddressRequired:"배송지를 입력해 주세요.",shippingAddressConfirm:"이 배송지를 브랜드에 공유할까요? 상품 발송에 사용됩니다.",shippingAddressFailed:"배송지를 공유하지 못했습니다. 입력 내용을 확인해 주세요.",
    productReceivedTitle:"상품을 받았다면",productReceivedBody:"상품이 도착하고 내용을 확인한 뒤 눌러 주세요. 확인 후 제작을 진행할 수 있습니다.",productReceivedButton:"상품을 받았습니다",productReceivedLoading:"변경 중...",productReceivedConfirm:"상품 수령을 완료로 표시할까요? 이후 납품 단계로 진행할 수 있습니다.",productReceivedFailed:"상품 수령 상태를 변경하지 못했습니다. 잠시 후 다시 시도해 주세요.",shippingStatusShared:"배송지 공유 완료",shippingStatusWaitingShipment:"발송 대기",shippingStatusShipped:"발송 완료",shippingStatusReceived:"수령 완료",shippingCarrier:"택배사",shippingTrackingNumber:"운송장 번호",shippedAt:"발송 일시",receivedAt:"수령 일시",
    deliveryTitle:"진행 완료 후 URL 제출",redeliveryTitle:"수정본 보내기",deliveryBody:"방문, 게시 또는 제작을 완료한 뒤 확인 가능한 게시물이나 결과물 URL을 보내 주세요.",deliveredPostUrlPlaceholder:"https://...",openDeliveredUrl:"제출한 URL 열기",deliver:"이 URL 보내기",redeliver:"수정본 보내기",updateDelivery:"URL 변경",delivering:"전송 중...",deliveryRequired:"확인 가능한 URL을 입력해 주세요.",deliveryFailed:"URL을 보내지 못했습니다. 주소를 확인한 후 다시 시도해 주세요.",
    accept:"주문 수락",decline:"이번에는 거절",accepting:"수락 중...",declining:"거절 중...",confirmAccept:"이 주문을 수락할까요? 수락 후 채팅으로 준비를 진행할 수 있습니다.",confirmDecline:"이 주문을 거절할까요? 거절하면 협업이 시작되지 않습니다.",confirmDeliver:"이 URL을 보낼까요?",confirmRedeliver:"이 URL을 수정본으로 보낼까요?",acceptFailed:"주문을 수락하지 못했습니다. 잠시 후 다시 시도해 주세요.",declineFailed:"주문을 거절하지 못했습니다. 잠시 후 다시 시도해 주세요.",authFailed:"로그인 정보를 확인할 수 없습니다.",
    productName:"상품·협업",productUrl:"상품 URL",projectType:"진행 방식",timing:"진행 시기",freeOffer:"상품 제공",secondaryUse:"사용 범위",yes:"있음",no:"없음",requestNote:"의뢰 내용",postInstructionTitle:"게시물에 넣을 내용",postInstructionBody:"게시물 마지막에 넣을 계정 태그와 해시태그입니다.",copyPostText:"복사",copied:"복사했습니다",postNotes:"게시물 요청 사항과 유의 사항",
    menuAndPayout:"PR 메뉴·수익",menuTitle:"PR 메뉴",deliverables:"납품 항목",price:"PR 메뉴 가격",payout:"예상 수익",transfer:"정산 반영",payoutPage:"수익 페이지 보기",payoutCardTitle:"이 협업의 예상 수익",payoutCardBody:"협업 완료 후 등록된 은행 계좌의 지급 예정 내역에 반영됩니다.",payoutMainLabel:"예상 수령액",payoutStatus:"반영 상태",payoutMinimum:"지급 기준",payoutDetails:"수익 상세",payoutDetailsSub:"예상 수수료와 공제 금액을 확인할 수 있습니다",payoutDetailMenuPrice:"PR 메뉴 가격",payoutDetailPayout:"예상 수익",payoutDetailBankFee:"이체 수수료(예상)",payoutDetailWithholding:"기타 공제",payoutDetailEstimatedNet:"예상 입금액",payoutImportantTitle:"정산 안내",payoutImportantBody:"표시된 금액은 현재 기준 예상액입니다. 최종 지급액은 협업 상태와 이체 수수료 등을 확인한 후 확정됩니다.",payoutOrderDates:"주문·정산 일정",payoutOrderDatesSub:"주문 수락일, 완료일과 지급일을 확인할 수 있습니다",payoutCreatedAt:"주문일",payoutAcceptedAt:"수락일",payoutCapturedAt:"결제 확정일",payoutCompletedAt:"완료일",payoutPaidAt:"지급일",payoutHoldNote:"현재 수익을 확인하고 있습니다. 필요한 경우 운영팀에서 연락드립니다.",payoutPaidNote:"이 협업의 수익이 지급되었습니다.",revisionTitle:"수정 요청",
    notSet:"미설정",noPostInstruction:"지정된 게시 문구가 없습니다.",referenceLoadFailed:"참고 자료를 불러오는 데 시간이 걸리고 있습니다. 잠시 후 다시 열어 주세요.",referenceOpen:"열기",referenceFile:"참고 파일",summaryMenu:"PR 메뉴",summaryPayout:"예상 수익",summaryDeadline:"마감일",detailSheetTitle:"주문 상세",detailSheetBody:"필요한 내용을 한곳에서 확인할 수 있도록 정리했습니다.",responseTitle:"이 주문을 진행할까요?",responseBody:"내용과 마감일을 확인한 후 진행할 수 있다면 주문을 수락해 주세요.",chatCtaTitle:"채팅으로 문의",chatCtaBody:"궁금한 점이나 진행 중 조율할 내용은 채팅에서 확인할 수 있습니다.",chatCtaButton:"채팅 열기",
  },
  "zh-TW": {
    loading:"載入中...",notFound:"找不到訂單。",back:"返回",titleFallback:"訂單詳情",menuContentTitle:"PR 方案資訊",orderContent:"訂單內容",preparationTitle:"開始前的準備事項",preparationBeforeAcceptTitle:"接受前請確認",preparationChatButton:"透過聊天室討論",preparationChatDisabled:"接受訂單後，可視需要透過聊天室討論細節。",preparationReadyLabel:"準備完成",preparationWaitingLabel:"需要確認",
    materialsConfirmTitle:"請確認素材與貼文資訊",materialsConfirmBody:"請確認收到的素材、發布條件、PR 標示與注意事項，確認無誤後完成此步驟。",materialsConfirmButton:"我已確認素材與貼文資訊",materialsConfirmLoading:"更新中...",materialsConfirmConfirm:"已確認所有素材與貼文資訊嗎？確認後即可進入交付階段。",materialsConfirmFailed:"無法更新素材確認狀態，請稍後再試。",materialsConfirmedTitle:"素材與貼文資訊已確認",materialsConfirmedBody:"目前可進行內容製作與交付。",
    shippingAddressTitle:"分享收件地址",shippingAddressBody:"請填寫商品收件地址，此資訊會分享給邀約品牌。",shippingRecipientName:"收件人",shippingPostalCode:"郵遞區號",shippingPrefecture:"縣市",shippingCity:"鄉鎮市區",shippingAddressLine1:"路名、門牌與建物名稱",shippingAddressLine2:"樓層或房號",shippingPhoneNumber:"電話號碼",shippingNotes:"配送備註",postalLookupButton:"自動填入",postalLookupLoading:"搜尋中...",postalLookupInvalid:"請輸入 7 碼郵遞區號。",postalLookupFailed:"無法自動填入地址，請手動輸入。",postalLookupNotFound:"找不到地址，請確認郵遞區號。",postalLookupApplied:"已填入地址，請補上門牌與建物資訊。",postalLookupMultiple:"找到多個結果，如有需要請從下方選擇其他地址。",postalLookupCandidateLabel:"地址選項",shippingShareAddress:"分享收件地址",shippingUpdateAddress:"更新收件地址",shippingSharingAddress:"分享中...",shippingAddressRequired:"請填寫收件地址。",shippingAddressConfirm:"要將這個收件地址分享給品牌嗎？此地址將用於寄送商品。",shippingAddressFailed:"無法分享收件地址，請確認填寫內容。",
    productReceivedTitle:"收到商品後",productReceivedBody:"商品送達並確認內容後，請點選此按鈕，即可繼續進行製作。",productReceivedButton:"我已收到商品",productReceivedLoading:"更新中...",productReceivedConfirm:"要將商品標示為已收到嗎？完成後即可進入交付階段。",productReceivedFailed:"無法更新商品收件狀態，請稍後再試。",shippingStatusShared:"已分享收件地址",shippingStatusWaitingShipment:"等待出貨",shippingStatusShipped:"已出貨",shippingStatusReceived:"已收件",shippingCarrier:"物流公司",shippingTrackingNumber:"物流單號",shippedAt:"出貨時間",receivedAt:"收件時間",
    deliveryTitle:"完成合作後提交 URL",redeliveryTitle:"提交修改版本",deliveryBody:"完成到訪、發布或製作後，請提交可供確認的貼文或成果 URL。",deliveredPostUrlPlaceholder:"https://...",openDeliveredUrl:"開啟已提交的 URL",deliver:"提交這個 URL",redeliver:"提交修改版本",updateDelivery:"更新 URL",delivering:"提交中...",deliveryRequired:"請輸入可供確認的 URL。",deliveryFailed:"無法提交 URL，請確認網址後再試一次。",
    accept:"接受訂單",decline:"這次先婉拒",accepting:"接受中...",declining:"婉拒中...",confirmAccept:"要接受這筆訂單嗎？接受後即可透過聊天室進行準備。",confirmDecline:"要婉拒這筆訂單嗎？婉拒後這筆合作不會開始。",confirmDeliver:"要提交這個 URL 嗎？",confirmRedeliver:"要將這個 URL 作為修改版本提交嗎？",acceptFailed:"無法接受訂單，請稍後再試。",declineFailed:"無法婉拒訂單，請稍後再試。",authFailed:"無法取得登入資訊。",
    productName:"商品／合作案件",productUrl:"商品 URL",projectType:"進行方式",timing:"執行時間",freeOffer:"提供商品",secondaryUse:"使用範圍",yes:"有",no:"無",requestNote:"邀約內容",postInstructionTitle:"貼文需加入的內容",postInstructionBody:"請放在貼文結尾的帳號標示與主題標籤。",copyPostText:"複製",copied:"已複製",postNotes:"貼文重點與注意事項",
    menuAndPayout:"PR 方案與收益",menuTitle:"PR 方案",deliverables:"交付項目",price:"PR 方案價格",payout:"預計收益",transfer:"收益狀態",payoutPage:"查看收益",payoutCardTitle:"這次合作的預計收益",payoutCardBody:"合作完成後，將列入已登記銀行帳戶的預計付款項目。",payoutMainLabel:"預計收取金額",payoutStatus:"目前狀態",payoutMinimum:"付款門檻",payoutDetails:"收益明細",payoutDetailsSub:"查看預估手續費與扣除項目",payoutDetailMenuPrice:"PR 方案價格",payoutDetailPayout:"預計收益",payoutDetailBankFee:"匯款手續費（預估）",payoutDetailWithholding:"其他扣除項目",payoutDetailEstimatedNet:"預計匯款金額",payoutImportantTitle:"收益付款說明",payoutImportantBody:"顯示金額為目前預估值，正式付款金額會在確認合作狀態與匯款手續費後確定。",payoutOrderDates:"訂單與付款時程",payoutOrderDatesSub:"查看接受訂單、完成合作與付款日期",payoutCreatedAt:"訂單日期",payoutAcceptedAt:"接受日期",payoutCapturedAt:"款項確認日期",payoutCompletedAt:"完成日期",payoutPaidAt:"付款日期",payoutHoldNote:"目前正在確認這筆收益，如有需要營運團隊會與你聯絡。",payoutPaidNote:"這次合作的收益已付款。",revisionTitle:"修改要求",
    notSet:"尚未設定",noPostInstruction:"品牌未指定貼文文字。",referenceLoadFailed:"參考資料載入時間較長，請稍後再開啟。",referenceOpen:"開啟",referenceFile:"參考檔案",summaryMenu:"PR 方案",summaryPayout:"預計收益",summaryDeadline:"截止日期",detailSheetTitle:"訂單詳情",detailSheetBody:"已整理需要確認的重要內容。",responseTitle:"要接受這筆訂單嗎？",responseBody:"請確認合作內容與截止日期，確定能配合後再接受訂單。",chatCtaTitle:"透過聊天室討論",chatCtaBody:"如有不清楚或需要協調的事項，可透過聊天室確認。",chatCtaButton:"開啟聊天室",
  },
};

export const creatorInquiryDictionary={
 ja:{loadFailed:"依頼を読み込めませんでした。",quoteLocked:"企業が回答済みのため、見積もりを変更できません。",quoteInvalid:"見積金額は1,000円以上の整数で入力してください。",quoteFailed:"見積もりを送信できませんでした。",quoteSavedMailFailed:"見積もりは保存されましたが、通知メールを送信できませんでした",quoteSent:"見積もりを送信しました",mailResent:"通知メールを再送しました",mailFailed:"通知メールを送信できませんでした",declineConfirm:"この依頼を辞退しますか？",declineFailed:"辞退できませんでした。",mailSubject:"Trendre Linkからのお問い合わせについて",back:"受注一覧へ戻る",simpleTitle:"仕事相談",title:"見積もり依頼",decline:"辞退",reload:"再読み込み",newInquiry:"新しいお問い合わせ",sentQuote:"送信済みの見積もり",expected:"受取予定額",note:"企業への備考",inquiry:"お問い合わせ",subject:"件名",inquiryBody:"お問い合わせ内容",sender:"送信者情報",name:"お名前",email:"メール",received:"受信日時",replyMail:"メールで返信する",request:"依頼内容",requestMode:"依頼形式",projectType:"案件タイプ",sns:"SNS",deliverables:"制作物・制作数",deliverable:"制作物",count:"制作数",usage:"利用用途",meeting:"打ち合わせ",conditions:"商品・条件・予算",product:"商品・サービス",productUrl:"商品URL",timing:"希望時期",budget:"予算",goal:"目的",freeOffer:"無償提供",yes:"あり",no:"なし",offerDetails:"提供内容",references:"特徴・参考情報",sellingPoints:"特徴・アピール",referenceUrl:"参考URL",additional:"その他の補足",company:"企業情報",companyBrand:"会社・ブランド",contact:"担当者",website:"Webサイト",companySns:"企業SNS",resending:"通知メールを再送しています…",resend:"通知メールを再送する",editQuote:"見積もりを確認・編集",createQuote:"見積もりを作成",close:"閉じる",amount:"見積金額",required:"必須",feeNote:"企業にはサービス手数料を加算した金額が表示されます。",optional:"任意",notePlaceholder:"企業へ伝えておきたいこと",sending:"送信中…",send:"見積もりを送信",quantity:(v:string)=>`数量: ${v}`,frequency:(v:string)=>`提供回数: ${v}`,people:(v:string)=>`対象人数: ${v}`,itemCount:(n:number)=>`${n}件`},
 en:{loadFailed:"Could not load the inquiry.",quoteLocked:"The brand has already responded, so this quote can no longer be changed.",quoteInvalid:"Enter a whole-number quote of at least JPY 1,000.",quoteFailed:"Could not send the quote.",quoteSavedMailFailed:"The quote was saved, but the notification email could not be sent",quoteSent:"Quote sent",mailResent:"Notification email resent",mailFailed:"Could not send the notification email",declineConfirm:"Decline this inquiry?",declineFailed:"Could not decline the inquiry.",mailSubject:"About your Trendre Link inquiry",back:"Back to orders",simpleTitle:"Work inquiry",title:"Quote request",decline:"Decline",reload:"Reload",newInquiry:"New inquiry",sentQuote:"Sent quote",expected:"Expected payout",note:"Note to the brand",inquiry:"Inquiry",subject:"Subject",inquiryBody:"Message",sender:"Sender details",name:"Name",email:"Email",received:"Received",replyMail:"Reply by email",request:"Request details",requestMode:"Request type",projectType:"Project type",sns:"SNS",deliverables:"Deliverables and quantity",deliverable:"Deliverables",count:"Quantity",usage:"Usage",meeting:"Meeting",conditions:"Product, terms, and budget",product:"Product or service",productUrl:"Product URL",timing:"Preferred timing",budget:"Budget",goal:"Goal",freeOffer:"Free offer",yes:"Yes",no:"No",offerDetails:"Offer details",references:"Highlights and references",sellingPoints:"Highlights",referenceUrl:"Reference URL",additional:"Additional notes",company:"Company details",companyBrand:"Company / brand",contact:"Contact",website:"Website",companySns:"Company social accounts",resending:"Resending notification…",resend:"Resend notification email",editQuote:"Review / edit quote",createQuote:"Create quote",close:"Close",amount:"Quote amount",required:"Required",feeNote:"The brand will see the amount including the service fee.",optional:"Optional",notePlaceholder:"Anything you want the brand to know",sending:"Sending…",send:"Send quote",quantity:(v:string)=>`Quantity: ${v}`,frequency:(v:string)=>`Offer frequency: ${v}`,people:(v:string)=>`People: ${v}`,itemCount:(n:number)=>`${n}`},
 ko:{loadFailed:"의뢰를 불러오지 못했습니다.",quoteLocked:"브랜드가 이미 답변하여 견적을 변경할 수 없습니다.",quoteInvalid:"견적 금액은 1,000엔 이상의 정수로 입력해 주세요.",quoteFailed:"견적을 보내지 못했습니다.",quoteSavedMailFailed:"견적은 저장했지만 알림 메일을 보내지 못했습니다",quoteSent:"견적을 보냈습니다",mailResent:"알림 메일을 다시 보냈습니다",mailFailed:"알림 메일을 보내지 못했습니다",declineConfirm:"이 의뢰를 거절할까요?",declineFailed:"의뢰를 거절하지 못했습니다.",mailSubject:"Trendre Link 문의 관련 안내",back:"의뢰 목록으로",simpleTitle:"협업 문의",title:"견적 요청",decline:"거절",reload:"다시 불러오기",newInquiry:"새로운 문의",sentQuote:"보낸 견적",expected:"예상 수익",note:"브랜드에게 전할 메모",inquiry:"문의 내용",subject:"제목",inquiryBody:"문의 내용",sender:"보낸 사람 정보",name:"이름",email:"이메일",received:"받은 일시",replyMail:"이메일로 답장",request:"의뢰 내용",requestMode:"의뢰 유형",projectType:"협업 유형",sns:"SNS",deliverables:"제작물 및 수량",deliverable:"제작물",count:"제작 수량",usage:"사용 목적",meeting:"미팅 방식",conditions:"상품·조건·예산",product:"상품·서비스",productUrl:"상품 URL",timing:"희망 일정",budget:"예산",goal:"목적",freeOffer:"무상 제공",yes:"있음",no:"없음",offerDetails:"제공 내용",references:"특징·참고 자료",sellingPoints:"특징·강점",referenceUrl:"참고 URL",additional:"추가 내용",company:"브랜드 정보",companyBrand:"기업·브랜드",contact:"담당자",website:"웹사이트",companySns:"브랜드 SNS",resending:"알림 메일을 다시 보내는 중…",resend:"알림 메일 다시 보내기",editQuote:"견적 확인·수정",createQuote:"견적 작성",close:"닫기",amount:"견적 금액",required:"필수",feeNote:"브랜드에는 서비스 수수료가 포함된 금액이 표시됩니다.",optional:"선택",notePlaceholder:"브랜드에게 미리 전할 내용을 입력하세요",sending:"전송 중…",send:"견적 보내기",quantity:(v:string)=>`수량: ${v}`,frequency:(v:string)=>`제공 횟수: ${v}`,people:(v:string)=>`대상 인원: ${v}`,itemCount:(n:number)=>`${n}개`},
 "zh-TW":{loadFailed:"無法載入合作邀約。",quoteLocked:"品牌已回覆，因此無法再修改報價。",quoteInvalid:"報價金額請輸入 1,000 日圓以上的整數。",quoteFailed:"無法送出報價。",quoteSavedMailFailed:"報價已儲存，但通知信件無法寄出",quoteSent:"報價已送出",mailResent:"通知信件已重新寄出",mailFailed:"無法寄出通知信件",declineConfirm:"要婉拒這則合作邀約嗎？",declineFailed:"無法婉拒合作邀約。",mailSubject:"關於 Trendre Link 的合作諮詢",back:"返回邀約列表",simpleTitle:"合作諮詢",title:"報價需求",decline:"婉拒",reload:"重新載入",newInquiry:"新的合作諮詢",sentQuote:"已送出的報價",expected:"預計收益",note:"給品牌的備註",inquiry:"諮詢內容",subject:"主旨",inquiryBody:"諮詢內容",sender:"寄件者資訊",name:"姓名",email:"電子郵件",received:"收到時間",replyMail:"以電子郵件回覆",request:"邀約內容",requestMode:"邀約形式",projectType:"合作類型",sns:"社群平台",deliverables:"製作內容與數量",deliverable:"製作內容",count:"製作數量",usage:"使用目的",meeting:"討論方式",conditions:"商品、條件與預算",product:"商品或服務",productUrl:"商品 URL",timing:"希望時間",budget:"預算",goal:"合作目的",freeOffer:"免費提供",yes:"有",no:"無",offerDetails:"提供內容",references:"特色與參考資料",sellingPoints:"特色與賣點",referenceUrl:"參考 URL",additional:"其他補充",company:"品牌資訊",companyBrand:"企業／品牌",contact:"聯絡人",website:"網站",companySns:"品牌社群帳號",resending:"正在重新寄送通知信件…",resend:"重新寄送通知信件",editQuote:"確認／編輯報價",createQuote:"建立報價",close:"關閉",amount:"報價金額",required:"必填",feeNote:"品牌端會顯示加上服務手續費後的金額。",optional:"選填",notePlaceholder:"輸入想先告知品牌的事項",sending:"送出中…",send:"送出報價",quantity:(v:string)=>`數量：${v}`,frequency:(v:string)=>`提供次數：${v}`,people:(v:string)=>`適用人數：${v}`,itemCount:(n:number)=>`${n} 項`},
} satisfies Record<AppLocale,Record<string,string|((value:any)=>string)>>;

export const creatorInquiryValueLabels:Record<AppLocale,Record<string,string>>={
 ja:{pr_post:"PR投稿",ugc:"UGC制作",visit_experience:"来店・体験",product_delivery:"商品提供",provided_assets:"素材提供",instagram:"Instagram",tiktok:"TikTok",x:"X",youtube:"YouTube",other:"その他",photo_image:"写真・画像素材",video:"動画素材",paid_ads:"広告で使用",owned_social:"自社SNSへ掲載",website_lp_ec:"自社Webサイト・LP・ECサイトへ掲載",digital_signage:"デジタルサイネージ・看板へ掲載",chat:"チャットで相談",in_person:"対面で打ち合わせ",online:"オンラインで打ち合わせ",not_needed:"打ち合わせ不要",awareness:"認知を広げたい",product_launch:"新商品を知ってほしい",sales:"購入につなげたい",store_visit:"来店を増やしたい",content_asset:"広告素材がほしい",feed_post:"フィード投稿",reel:"リール",stories:"ストーリーズ",live_stream:"ライブ配信",short_video:"ショート動画",standard_post:"通常投稿",thread_post:"スレッド投稿",video_post:"動画投稿",long_video:"長尺動画",feed:"フィード投稿",story:"ストーリーズ",photo:"写真素材",live:"ライブ配信",product_review:"商品レビュー",visit_event:"来店・体験",provided:"商品・サービスを提供する",not_provided:"提供なし",consult:"相談して決める",organic:"自社SNS・Webサイトで利用",none:"二次利用なし",undecided:"相談して決める"},
 en:{pr_post:"PR post",ugc:"UGC creation",visit_experience:"Store visit / experience",product_delivery:"Product provided",provided_assets:"Assets provided",instagram:"Instagram",tiktok:"TikTok",x:"X",youtube:"YouTube",other:"Other",photo_image:"Photo / image assets",video:"Video assets",paid_ads:"Paid ads",owned_social:"Brand social accounts",website_lp_ec:"Brand website / landing page / shop",digital_signage:"Digital signage / outdoor ads",chat:"Discuss by chat",in_person:"Meet in person",online:"Meet online",not_needed:"No meeting needed",awareness:"Grow awareness",product_launch:"Promote a new product",sales:"Drive purchases",store_visit:"Increase store visits",content_asset:"Create ad assets",feed_post:"Feed post",reel:"Reel",stories:"Stories",live_stream:"Live stream",short_video:"Short video",standard_post:"Standard post",thread_post:"Thread",video_post:"Video post",long_video:"Long-form video",feed:"Feed post",story:"Story",photo:"Photo assets",live:"Live stream",product_review:"Product review",visit_event:"Store visit / experience",provided:"Product / service provided",not_provided:"Nothing provided",consult:"Discuss together",organic:"Brand social accounts / website",none:"No secondary use",undecided:"Discuss together"},
 ko:{pr_post:"PR 게시물",ugc:"UGC 제작",visit_experience:"매장 방문·체험",product_delivery:"상품 제공",provided_assets:"소재 제공",instagram:"Instagram",tiktok:"TikTok",x:"X",youtube:"YouTube",other:"기타",photo_image:"사진·이미지 소재",video:"영상 소재",paid_ads:"광고 활용",owned_social:"브랜드 SNS 게시",website_lp_ec:"브랜드 웹사이트·랜딩 페이지·쇼핑몰 게시",digital_signage:"디지털 사이니지·옥외 광고 게시",chat:"채팅으로 협의",in_person:"대면 미팅",online:"온라인 미팅",not_needed:"미팅 불필요",awareness:"인지도 확대",product_launch:"신제품 홍보",sales:"구매 전환",store_visit:"매장 방문 확대",content_asset:"광고 소재 제작",feed_post:"피드 게시물",reel:"릴스",stories:"스토리",live_stream:"라이브 방송",short_video:"숏폼 영상",standard_post:"일반 게시물",thread_post:"스레드 게시물",video_post:"영상 게시물",long_video:"롱폼 영상",feed:"피드 게시물",story:"스토리",photo:"사진 소재",live:"라이브 방송",product_review:"상품 리뷰",visit_event:"매장 방문·체험",provided:"상품·서비스 제공",not_provided:"제공 없음",consult:"협의 후 결정",organic:"브랜드 SNS·웹사이트 활용",none:"2차 활용 없음",undecided:"협의 후 결정"},
 "zh-TW":{pr_post:"PR 貼文",ugc:"UGC 製作",visit_experience:"到店／體驗",product_delivery:"提供商品",provided_assets:"提供素材",instagram:"Instagram",tiktok:"TikTok",x:"X",youtube:"YouTube",other:"其他",photo_image:"照片／圖片素材",video:"影片素材",paid_ads:"用於廣告",owned_social:"刊登於品牌社群帳號",website_lp_ec:"刊登於品牌網站、活動頁面或購物網站",digital_signage:"刊登於數位看板或戶外廣告",chat:"透過聊天室討論",in_person:"面對面討論",online:"線上討論",not_needed:"不需討論",awareness:"提升知名度",product_launch:"宣傳新商品",sales:"促進購買",store_visit:"增加到店人數",content_asset:"製作廣告素材",feed_post:"動態貼文",reel:"Reels",stories:"限時動態",live_stream:"直播",short_video:"短影音",standard_post:"一般貼文",thread_post:"串文",video_post:"影片貼文",long_video:"長影片",feed:"動態貼文",story:"限時動態",photo:"照片素材",live:"直播",product_review:"商品評測",visit_event:"到店／體驗",provided:"提供商品或服務",not_provided:"不提供",consult:"討論後決定",organic:"用於品牌社群帳號或網站",none:"不開放二次使用",undecided:"討論後決定"},
};
